# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  # Don't fail status checks for missing coverage
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

# Coverage flags for different architectures
flag_management:
  individual_flags:
    - name: x86_64-linux
      carryforward: true
    - name: aarch64-linux
      carryforward: true
    - name: aarch64-darwin
      carryforward: true
