# SPDX-FileCopyrightText: 2026 Jörg Thalheim
# SPDX-License-Identifier: MIT

[package]
name                 = "harmonia-store-gc"
version.workspace    = true
authors.workspace    = true
edition.workspace    = true
license.workspace    = true
homepage.workspace   = true
repository.workspace = true
description          = "Garbage collection for the Nix store"

[[bin]]
name = "harmonia-gc"
path = "src/bin/harmonia-gc.rs"

[dependencies]
clap                = { workspace = true }
foldhash            = { workspace = true }
harmonia-store-db   = { workspace = true }
harmonia-store-fs   = { workspace = true }
harmonia-store-path = { workspace = true }
memchr              = { workspace = true }
nix                 = { workspace = true }
rayon               = { workspace = true }
thiserror           = { workspace = true }
tracing             = { workspace = true }
tracing-subscriber  = { workspace = true }
walkdir             = { workspace = true }

[dev-dependencies]
rand     = { workspace = true }
rusqlite = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
